"""Generate the messy multi-source dataset for the Excel / Power Query case
study. The mess is DESIGNED — every defect is a specific Power Query
technique the case study demonstrates:

  monthly exports: drifting column names month to month, three date formats,
                   currency as text with $ and commas, inconsistent region
                   casing/whitespace, footer junk rows
  budget_wide:     pivot-shaped (regions x month columns) -> unpivot
  product_lookup:  duplicate keys, trailing spaces, mixed-case SKUs
"""

import csv
import pathlib
import random

rng = random.Random(20260708)
OUT = pathlib.Path(__file__).parent / "data"

REGIONS = ["North", "South", "East", "West"]
REGION_MESS = lambda r: rng.choice([r, r.upper(), r.lower(), f" {r}", f"{r} "])
PRODUCTS = [f"SKU-{i:03d}" for i in range(1, 41)]

MONTHS = [("jan", "01", 31), ("feb", "02", 28), ("mar", "03", 31),
          ("apr", "04", 30), ("may", "05", 31), ("jun", "06", 30)]

# header drift: same 6 logical columns, three naming conventions
HEADERS = [
    ["Order ID", "Order Date", "Region", "SKU", "Qty", "Sale Amount"],
    ["order_id", "order_date", "region", "sku", "quantity", "amount"],
    ["OrderID", "Date", "Sales Region", "Product SKU", "Units", "Revenue ($)"],
]

def fmt_date(y, m, d, style):
    if style == 0:
        return f"{m}/{d:02d}/{y}"                      # 06/15/2026
    if style == 1:
        return f"{d:02d}-{['','Jan','Feb','Mar','Apr','May','Jun'][int(m)]}-{str(y)[2:]}"  # 15-Jun-26
    return f"{y}-{m}-{d:02d}"                          # ISO

oid = 10_000
for i, (name, mnum, days) in enumerate(MONTHS):
    header = HEADERS[i % 3]
    date_style = i % 3
    rows = []
    for _ in range(rng.randint(180, 260)):
        oid += 1
        d = rng.randint(1, days)
        qty = rng.randint(1, 12)
        amount = qty * rng.uniform(9, 180)
        rows.append([
            f"ORD{oid}",
            fmt_date(2026, mnum, d, date_style),
            REGION_MESS(rng.choice(REGIONS)),
            rng.choice(PRODUCTS) if rng.random() > 0.03 else rng.choice(PRODUCTS).lower(),
            qty,
            f"${amount:,.2f}",                      # currency AS TEXT
        ])
    with open(OUT / "exports" / f"sales_{name}_2026.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(header)
        w.writerows(rows)
        # footer junk (the classic export tail)
        w.writerow([])
        w.writerow([f"Total: {len(rows)} orders", "", "", "", "", ""])
        w.writerow(["Generated by LegacySalesSystem v2.3", "", "", "", "", ""])

# budget: wide/pivot-shaped
with open(OUT / "budget_wide.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["Region", "Jan Budget", "Feb Budget", "Mar Budget",
                "Apr Budget", "May Budget", "Jun Budget"])
    for r in REGIONS:
        w.writerow([r] + [round(rng.uniform(28_000, 45_000), 0) for _ in MONTHS])

# product lookup with planted defects
with open(OUT / "product_lookup.csv", "w", newline="") as f:
    w = csv.writer(f)
    w.writerow(["SKU", "Product Name", "Category", "Unit Cost"])
    for p in PRODUCTS:
        w.writerow([p, f"Product {p[-3:]}", rng.choice(["Hardware", "Software", "Services"]),
                    round(rng.uniform(4, 90), 2)])
    # duplicates with whitespace + case variants (the vlookup killers)
    w.writerow(["SKU-001 ", "Product 001", "Hardware", 12.50])
    w.writerow(["sku-002", "Product 002 OLD NAME", "Hardware", 11.00])
    w.writerow(["SKU-003", "Product 003", "Hardware", 8.75])  # exact dup key, diff cost

print("files:", sorted(p.name for p in (OUT / "exports").iterdir()),
      "+ budget_wide.csv, product_lookup.csv")
