"""Executable reference for the Power Query contracts; writes tidy CSVs and audit totals."""
from pathlib import Path
from datetime import datetime
from decimal import Decimal
import csv
import json

ROOT = Path(__file__).parent
ALIASES = {
    'Order ID':'order_id', 'order_id':'order_id', 'OrderID':'order_id',
    'Order Date':'order_date', 'order_date':'order_date', 'Date':'order_date',
    'Region':'region', 'region':'region', 'Sales Region':'region',
    'SKU':'sku', 'sku':'sku', 'Product SKU':'sku',
    'Qty':'quantity', 'quantity':'quantity', 'Units':'quantity',
    'Sale Amount':'amount', 'amount':'amount', 'Revenue ($)':'amount',
}

def parse_date(value):
    for fmt in ('%Y-%m-%d', '%m/%d/%Y', '%d-%b-%y'):
        try: return datetime.strptime(value, fmt).date().isoformat()
        except ValueError: pass
    raise ValueError(f'Unsupported date: {value}')

def clean(data=ROOT/'data'):
    products={}; duplicate_products=0
    with (data/'product_lookup.csv').open(newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            sku=row['SKU'].strip().upper()
            if sku in products:
                duplicate_products+=1
                continue  # Source row order is the explicit survivor rule.
            products[sku]={'sku':sku, 'name':row['Product Name'], 'category':row['Category'],
                           'unit_cost':float(Decimal(row['Unit Cost']))}
    sales=[]; seen=set(); footer_rows=0
    for path in sorted((data/'exports').glob('*.csv')):
        with path.open(newline='', encoding='utf-8') as f:
            reader=csv.DictReader(f)
            if any(h not in ALIASES for h in reader.fieldnames):
                raise ValueError(f'Unknown column in {path.name}')
            fields=[ALIASES[h] for h in reader.fieldnames]
            if len(fields)!=6 or len(set(fields))!=6:
                raise ValueError(f'Missing or duplicate logical column in {path.name}')
            for original in reader:
                row={ALIASES[k]:v for k,v in original.items()}
                if not row['order_id'].startswith('ORD'):
                    if row['order_id'].startswith(('Total:', 'Generated by')):
                        footer_rows+=1; continue
                    raise ValueError('Unexpected non-order row')
                if row['order_id'] in seen: raise ValueError('Duplicate order ID')
                seen.add(row['order_id'])
                row['sku']=row['sku'].strip().upper()
                if row['sku'] not in products: raise ValueError('Unknown SKU')
                row['region']=row['region'].strip().title()
                if row['region'] not in {'North','South','East','West'}: raise ValueError('Unknown region')
                row['order_date']=parse_date(row['order_date'])
                row['month']=row['order_date'][:7]
                row['quantity']=int(row['quantity'])
                amount=Decimal(row['amount'].replace('$','').replace(',',''))
                if not amount.is_finite() or amount < 0 or row['quantity']<=0: raise ValueError('Invalid amount/quantity')
                row['amount']=float(amount)
                row['cost']=float(Decimal(str(products[row['sku']]['unit_cost']))*row['quantity'])
                row['source_file']=path.name
                sales.append(row)
    budgets=[]
    with (data/'budget_wide.csv').open(newline='', encoding='utf-8') as f:
        for row in csv.DictReader(f):
            for label, value in row.items():
                if label=='Region': continue
                month=datetime.strptime(label, '%b Budget').month
                budgets.append({'region':row['Region'], 'month':f'2026-{month:02d}', 'budget':float(Decimal(value))})
    return {'sales':sales, 'products':list(products.values()), 'budget':budgets,
            'audit':{'orders':len(sales),'footer_rows_removed':footer_rows,
                     'duplicate_product_keys_removed':duplicate_products,
                     'revenue':float(sum(Decimal(str(r['amount'])) for r in sales)),
                     'budget':sum(r['budget'] for r in budgets)}}

def main():
    result=clean(); out=ROOT/'outputs'; out.mkdir(exist_ok=True)
    for key in ('sales','products','budget'):
        with (out/f'{key}.csv').open('w', newline='', encoding='utf-8') as f:
            writer=csv.DictWriter(f,fieldnames=result[key][0]); writer.writeheader(); writer.writerows(result[key])
    (out/'workbook_data.json').write_text(json.dumps(result,indent=2),encoding='utf-8')
    print(json.dumps(result['audit'],indent=2))

if __name__=='__main__': main()
